<?php
declare(strict_types=1);

/**
 * Installation Helper Functions
 * Called by ajax.php during the setup wizard install action.
 */

// ─────────────────────────────────────────────────────────────────────────────
// createEnvFile
// Writes a .env file to the project root with all required variables.
// ─────────────────────────────────────────────────────────────────────────────
function createEnvFile(string $rootDir, array $data): void
{
    $jwtSecret  = bin2hex(random_bytes(32));   // 64 hex chars
    $appKey     = 'base64:' . base64_encode(random_bytes(32));
    $appName    = $data['app_name'] ?? 'AI Recruit';
    $appUrl     = $data['app_url']  ?? 'http://localhost';
    $dbHost     = $data['db_host']  ?? '127.0.0.1';
    $dbPort     = $data['db_port']  ?? '3306';
    $dbName     = $data['db_name']  ?? 'ai_recruitment';
    $dbUser     = $data['db_user']  ?? 'root';
    $dbPass     = $data['db_pass']  ?? '';

    // Escape values containing spaces or special chars for .env
    $escape = static function (string $val): string {
        if (preg_match('/[\s"\'\\\\#]/', $val)) {
            return '"' . addslashes($val) . '"';
        }
        return $val;
    };

    $env = <<<EOT
# ============================================================
# AI Recruitment SaaS Platform — Environment Configuration
# Generated by Setup Wizard on {$_SERVER['REQUEST_TIME_FLOAT']} UTC
# ============================================================

# Application
APP_NAME={$escape($appName)}
APP_URL={$escape($appUrl)}
APP_ENV=production
APP_KEY={$appKey}
APP_DEBUG=false

# Database
DB_HOST={$escape($dbHost)}
DB_PORT={$dbPort}
DB_NAME={$escape($dbName)}
DB_USERNAME={$escape($dbUser)}
DB_PASSWORD={$escape($dbPass)}

# Authentication (JWT)
JWT_SECRET={$jwtSecret}
JWT_EXPIRY=86400

# Mail
MAIL_DRIVER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=587
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_FROM_ADDRESS=noreply@example.com
MAIL_FROM_NAME={$escape($appName)}
MAIL_ENCRYPTION=tls

# File uploads
UPLOAD_MAX_SIZE=10240
UPLOAD_ALLOWED_TYPES=pdf,doc,docx,jpg,jpeg,png,gif,mp4,webm

# Session
SESSION_LIFETIME=120

EOT;

    $path = $rootDir . '/.env';
    if (file_put_contents($path, $env) === false) {
        throw new RuntimeException("Cannot write to {$path}. Check directory permissions.");
    }
    chmod($path, 0600);
}

// ─────────────────────────────────────────────────────────────────────────────
// runSchema
// Reads /database/schema.sql and executes each statement.
// ─────────────────────────────────────────────────────────────────────────────
function runSchema(PDO $pdo, string $rootDir): void
{
    $schemaFile = $rootDir . '/database/schema.sql';
    if (!file_exists($schemaFile)) {
        throw new RuntimeException("Schema file not found: {$schemaFile}");
    }

    $sql = file_get_contents($schemaFile);
    if ($sql === false) {
        throw new RuntimeException("Cannot read schema file: {$schemaFile}");
    }

    // Split on semicolons but handle DELIMITER blocks safely
    // Remove comments first
    $sql = preg_replace('/--[^\n]*\n/', "\n", $sql);
    $sql = preg_replace('/\/\*.*?\*\//s', '', $sql);

    // Split and execute
    $statements = array_filter(
        array_map('trim', explode(';', $sql)),
        static fn(string $s) => strlen($s) > 0
    );

    foreach ($statements as $statement) {
        if (trim($statement) === '') continue;
        try {
            $pdo->exec($statement);
        } catch (PDOException $e) {
            // Skip duplicate-definition errors (schema already partially applied)
            if (!in_array($e->getCode(), ['42S01', '42000'], true)) {
                // Only throw for non-duplicate-table errors
                if (str_contains($e->getMessage(), 'already exists')) continue;
                throw $e;
            }
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// seedDefaultData
// Inserts roles, permissions, onboarding steps and other default records.
// ─────────────────────────────────────────────────────────────────────────────
function seedDefaultData(PDO $pdo): void
{
    // ── Roles ──────────────────────────────────────────────────────────────────
    $roles = [
        ['name' => 'Super Admin',   'slug' => 'super-admin',    'description' => 'Full platform access.',           'is_system' => 1],
        ['name' => 'Admin',         'slug' => 'admin',          'description' => 'Tenant administrator.',           'is_system' => 1],
        ['name' => 'Recruiter',     'slug' => 'recruiter',      'description' => 'Manages jobs and candidates.',    'is_system' => 1],
        ['name' => 'Hiring Manager','slug' => 'hiring-manager', 'description' => 'Reviews candidates & interviews.','is_system' => 1],
        ['name' => 'Interviewer',   'slug' => 'interviewer',    'description' => 'Conducts interviews.',            'is_system' => 1],
        ['name' => 'Viewer',        'slug' => 'viewer',         'description' => 'Read-only access.',               'is_system' => 1],
    ];

    $roleStmt = $pdo->prepare(
        "INSERT IGNORE INTO `roles` (`name`, `slug`, `description`, `is_system`) VALUES (?, ?, ?, ?)"
    );
    foreach ($roles as $r) {
        $roleStmt->execute([$r['name'], $r['slug'], $r['description'], $r['is_system']]);
    }

    // ── Permissions ────────────────────────────────────────────────────────────
    $permissions = [
        // Jobs
        ['Jobs: View All',         'jobs.view',         'jobs'],
        ['Jobs: Create',           'jobs.create',       'jobs'],
        ['Jobs: Edit',             'jobs.edit',         'jobs'],
        ['Jobs: Delete',           'jobs.delete',       'jobs'],
        ['Jobs: Publish',          'jobs.publish',      'jobs'],
        // Candidates
        ['Candidates: View',       'candidates.view',   'candidates'],
        ['Candidates: Create',     'candidates.create', 'candidates'],
        ['Candidates: Edit',       'candidates.edit',   'candidates'],
        ['Candidates: Delete',     'candidates.delete', 'candidates'],
        ['Candidates: Export',     'candidates.export', 'candidates'],
        // Interviews
        ['Interviews: View',       'interviews.view',   'interviews'],
        ['Interviews: Schedule',   'interviews.schedule','interviews'],
        ['Interviews: Conduct',    'interviews.conduct','interviews'],
        ['Interviews: Review',     'interviews.review', 'interviews'],
        // Applications
        ['Applications: View',     'applications.view', 'applications'],
        ['Applications: Move',     'applications.move', 'applications'],
        ['Applications: Reject',   'applications.reject','applications'],
        // Reports
        ['Reports: View',          'reports.view',      'reports'],
        ['Reports: Export',        'reports.export',    'reports'],
        // Settings
        ['Settings: View',         'settings.view',     'settings'],
        ['Settings: Edit',         'settings.edit',     'settings'],
        // Users
        ['Users: View',            'users.view',        'users'],
        ['Users: Create',          'users.create',      'users'],
        ['Users: Edit',            'users.edit',        'users'],
        ['Users: Delete',          'users.delete',      'users'],
        ['Users: Impersonate',     'users.impersonate', 'users'],
        // AI
        ['AI: Configure',          'ai.configure',      'ai'],
        ['AI: Use Features',       'ai.use',            'ai'],
        // Tenants (super-admin only)
        ['Tenants: Manage',        'tenants.manage',    'tenants'],
        ['Tenants: Create',        'tenants.create',    'tenants'],
        ['Tenants: Delete',        'tenants.delete',    'tenants'],
    ];

    $permStmt = $pdo->prepare(
        "INSERT IGNORE INTO `permissions` (`name`, `slug`, `group_name`) VALUES (?, ?, ?)"
    );
    foreach ($permissions as $p) {
        $permStmt->execute($p);
    }

    // ── Assign all permissions to super-admin role ─────────────────────────────
    $superRole = $pdo->query("SELECT id FROM `roles` WHERE `slug` = 'super-admin' LIMIT 1")->fetch();
    if ($superRole) {
        $allPerms = $pdo->query("SELECT id FROM `permissions`")->fetchAll(PDO::FETCH_COLUMN);
        $rpStmt   = $pdo->prepare("INSERT IGNORE INTO `role_permissions` (`role_id`, `permission_id`) VALUES (?, ?)");
        foreach ($allPerms as $pid) {
            $rpStmt->execute([$superRole['id'], $pid]);
        }
    }

    // ── Assign relevant permissions to admin role ──────────────────────────────
    $adminRole = $pdo->query("SELECT id FROM `roles` WHERE `slug` = 'admin' LIMIT 1")->fetch();
    if ($adminRole) {
        $adminSlugs = [
            'jobs.view','jobs.create','jobs.edit','jobs.delete','jobs.publish',
            'candidates.view','candidates.create','candidates.edit','candidates.delete','candidates.export',
            'interviews.view','interviews.schedule','interviews.conduct','interviews.review',
            'applications.view','applications.move','applications.reject',
            'reports.view','reports.export',
            'settings.view','settings.edit',
            'users.view','users.create','users.edit','users.delete',
            'ai.configure','ai.use',
        ];
        $placeholders = implode(',', array_fill(0, count($adminSlugs), '?'));
        $adminPerms   = $pdo->prepare("SELECT id FROM `permissions` WHERE `slug` IN ({$placeholders})")
            ->execute($adminSlugs) ? $pdo->query("SELECT id FROM `permissions` WHERE `slug` IN ('" . implode("','", $adminSlugs) . "')")->fetchAll(PDO::FETCH_COLUMN) : [];
        $rpStmt2 = $pdo->prepare("INSERT IGNORE INTO `role_permissions` (`role_id`, `permission_id`) VALUES (?, ?)");
        foreach ($adminPerms as $pid) {
            $rpStmt2->execute([$adminRole['id'], $pid]);
        }
    }

    // ── Onboarding steps (if table exists) ────────────────────────────────────
    seedOnboardingSteps($pdo);
}

// ─────────────────────────────────────────────────────────────────────────────
// seedOnboardingSteps
// Inserts default onboarding checklist items.
// ─────────────────────────────────────────────────────────────────────────────
function seedOnboardingSteps(PDO $pdo): void
{
    // Check if table exists
    try {
        $pdo->query("SELECT 1 FROM `onboarding_steps` LIMIT 1");
    } catch (PDOException) {
        return; // Table doesn't exist, skip
    }

    $steps = [
        ['title' => 'Complete your profile',    'description' => 'Add your personal details and profile photo.',  'order' => 1, 'type' => 'profile'],
        ['title' => 'Configure AI settings',    'description' => 'Connect your OpenAI key to enable AI features.','order' => 2, 'type' => 'ai_setup'],
        ['title' => 'Create your first job',    'description' => 'Post a job opening to start receiving applications.','order' => 3, 'type' => 'first_job'],
        ['title' => 'Invite team members',      'description' => 'Add recruiters and hiring managers to your team.','order' => 4, 'type' => 'invite_team'],
        ['title' => 'Set up email templates',   'description' => 'Customise candidate communication templates.',   'order' => 5, 'type' => 'email_templates'],
        ['title' => 'Review pipeline stages',   'description' => 'Configure your hiring pipeline stages.',         'order' => 6, 'type' => 'pipeline'],
    ];

    $stmt = $pdo->prepare(
        "INSERT IGNORE INTO `onboarding_steps` (`title`, `description`, `order`, `type`) VALUES (?, ?, ?, ?)"
    );
    foreach ($steps as $s) {
        $stmt->execute([$s['title'], $s['description'], $s['order'], $s['type']]);
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// seedSystemSettings
// Writes key/value pairs to system_settings table.
// ─────────────────────────────────────────────────────────────────────────────
function seedSystemSettings(PDO $pdo, string $appUrl, string $appName): void
{
    $settings = [
        ['app_name',               $appName,     'general'],
        ['app_url',                $appUrl,      'general'],
        ['app_version',            '1.0.0',      'general'],
        ['default_language',       'en',         'general'],
        ['default_timezone',       'UTC',        'general'],
        ['registration_enabled',   '1',          'general'],
        ['max_tenants',            '100',        'general'],
        ['ai_enabled',             '1',          'ai'],
        ['video_interviews_enabled','1',         'ai'],
        ['max_file_upload_mb',     '10',         'uploads'],
        ['allowed_file_types',     'pdf,doc,docx,jpg,jpeg,png', 'uploads'],
        ['session_lifetime_mins',  '120',        'session'],
        ['installed_version',      '1.0.0',      'system'],
        ['installed_at',           date('Y-m-d H:i:s'), 'system'],
    ];

    $stmt = $pdo->prepare(
        "INSERT INTO `system_settings` (`key`, `value`, `group_name`) VALUES (?, ?, ?)
         ON DUPLICATE KEY UPDATE `value` = VALUES(`value`)"
    );
    foreach ($settings as $s) {
        $stmt->execute($s);
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// createSuperAdmin
// Creates the super admin user record.
// Returns the new user ID.
// ─────────────────────────────────────────────────────────────────────────────
function createSuperAdmin(PDO $pdo, array $data): int
{
    $passwordHash = password_hash($data['password'], PASSWORD_BCRYPT, ['cost' => 12]);

    // Check for existing user
    $existing = $pdo->prepare("SELECT id FROM `users` WHERE `email` = ? LIMIT 1");
    $existing->execute([$data['email']]);
    $row = $existing->fetch();
    if ($row) {
        // Update existing user to super admin
        $pdo->prepare(
            "UPDATE `users` SET
                `first_name`           = ?,
                `last_name`            = ?,
                `password_hash`        = ?,
                `is_super_admin`       = 1,
                `status`               = 'active',
                `email_verified_at`    = NOW(),
                `onboarding_completed` = 0,
                `tenant_id`            = ?
             WHERE `email` = ?"
        )->execute([$data['first_name'], $data['last_name'], $passwordHash, $data['tenant_id'], $data['email']]);
        return (int)$row['id'];
    }

    $stmt = $pdo->prepare(
        "INSERT INTO `users`
            (`tenant_id`, `first_name`, `last_name`, `email`, `password_hash`,
             `is_super_admin`, `status`, `email_verified_at`, `onboarding_completed`)
         VALUES
            (?, ?, ?, ?, ?, 1, 'active', NOW(), 0)"
    );
    $stmt->execute([
        $data['tenant_id'],
        $data['first_name'],
        $data['last_name'],
        $data['email'],
        $passwordHash,
    ]);

    $newId = (int)$pdo->lastInsertId();
    if ($newId === 0) {
        throw new RuntimeException('Failed to retrieve new user ID after insert.');
    }
    return $newId;
}

// ─────────────────────────────────────────────────────────────────────────────
// createDefaultTenant
// Inserts the first company/tenant record.
// Returns the new tenant ID.
// ─────────────────────────────────────────────────────────────────────────────
function createDefaultTenant(PDO $pdo, array $data): int
{
    // Check for existing slug
    $existing = $pdo->prepare("SELECT id FROM `tenants` WHERE `slug` = ? LIMIT 1");
    $existing->execute([$data['slug']]);
    $row = $existing->fetch();
    if ($row) {
        // Update existing tenant
        $pdo->prepare(
            "UPDATE `tenants` SET `name` = ?, `domain` = ?, `status` = 'active', `plan` = 'enterprise' WHERE `id` = ?"
        )->execute([$data['name'], $data['domain'], $row['id']]);
        return (int)$row['id'];
    }

    $stmt = $pdo->prepare(
        "INSERT INTO `tenants` (`name`, `slug`, `domain`, `status`, `plan`)
         VALUES (?, ?, ?, 'active', 'enterprise')"
    );
    $stmt->execute([$data['name'], $data['slug'], $data['domain']]);

    $newId = (int)$pdo->lastInsertId();
    if ($newId === 0) {
        throw new RuntimeException('Failed to retrieve new tenant ID after insert.');
    }

    // Seed AI settings for the tenant
    try {
        $pdo->prepare(
            "INSERT IGNORE INTO `tenant_ai_settings`
                (`tenant_id`, `enable_video_interviews`, `enable_voice_interviews`, `enable_text_interviews`)
             VALUES (?, 1, 1, 1)"
        )->execute([$newId]);
    } catch (Throwable) {
        // Non-fatal: table may not exist yet
    }

    return $newId;
}
