"""
app/models/strategy.py
──────────────────────
MarketingStrategy, BrandGuideline, ContentPlan, TargetAudience,
BusinessGoal, CompetitorRef models.
"""
from __future__ import annotations

import enum
import uuid
from datetime import datetime
from typing import TYPE_CHECKING, List, Optional

from sqlalchemy import (
    Boolean,
    DateTime,
    Enum,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base

if TYPE_CHECKING:
    from app.models.user import User
    from app.models.content import ContentPiece


# ─── Enums ────────────────────────────────────────────────────────────────────

class StrategyStatus(str, enum.Enum):
    DRAFT = "draft"
    ACTIVE = "active"
    PAUSED = "paused"
    ARCHIVED = "archived"


class GoalType(str, enum.Enum):
    BRAND_AWARENESS = "brand_awareness"
    LEAD_GENERATION = "lead_generation"
    COMMUNITY_GROWTH = "community_growth"
    SALES_CONVERSION = "sales_conversion"
    THOUGHT_LEADERSHIP = "thought_leadership"
    CUSTOMER_RETENTION = "customer_retention"
    EMPLOYER_BRANDING = "employer_branding"
    PRODUCT_LAUNCH = "product_launch"
    CRISIS_MANAGEMENT = "crisis_management"


class GoalStatus(str, enum.Enum):
    NOT_STARTED = "not_started"
    IN_PROGRESS = "in_progress"
    ON_TRACK = "on_track"
    AT_RISK = "at_risk"
    COMPLETED = "completed"
    MISSED = "missed"


class AudienceAgeGroup(str, enum.Enum):
    GEN_Z = "gen_z"          # 18–26
    MILLENNIAL = "millennial" # 27–42
    GEN_X = "gen_x"          # 43–58
    BOOMER = "boomer"        # 59+
    ALL_AGES = "all_ages"


class ContentPlanStatus(str, enum.Enum):
    DRAFT = "draft"
    ACTIVE = "active"
    COMPLETED = "completed"
    ARCHIVED = "archived"


# ─── Marketing Strategy Model ─────────────────────────────────────────────────

class MarketingStrategy(Base):
    """
    Top-level marketing strategy for a user's brand / business.
    Generated by AI agents or created manually.
    """
    __tablename__ = "marketing_strategies"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    status: Mapped[StrategyStatus] = mapped_column(
        Enum(StrategyStatus), default=StrategyStatus.DRAFT, nullable=False, index=True
    )

    # Strategy context (AI-parsed brand voice, positioning, etc.)
    brand_voice: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    unique_value_proposition: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    competitive_advantages: Mapped[Optional[list]] = mapped_column(JSONB, nullable=True, default=list)
    target_platforms: Mapped[Optional[list]] = mapped_column(JSONB, nullable=True, default=list)
    posting_frequency: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True, default=dict)
    optimal_posting_times: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True, default=dict)
    content_mix: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True, default=dict)

    # AI generation metadata
    ai_generated: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    ai_model_used: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    generation_prompt: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    generation_metadata: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True)

    # Strategy period
    start_date: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    end_date: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)

    # Soft delete
    deleted_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )

    # Relationships
    owner: Mapped["User"] = relationship("User", back_populates="strategies")
    brand_guidelines: Mapped[List["BrandGuideline"]] = relationship(
        "BrandGuideline", back_populates="strategy", cascade="all, delete-orphan"
    )
    content_plans: Mapped[List["ContentPlan"]] = relationship(
        "ContentPlan", back_populates="strategy", cascade="all, delete-orphan"
    )
    target_audiences: Mapped[List["TargetAudience"]] = relationship(
        "TargetAudience", back_populates="strategy", cascade="all, delete-orphan"
    )
    business_goals: Mapped[List["BusinessGoal"]] = relationship(
        "BusinessGoal", back_populates="strategy", cascade="all, delete-orphan"
    )
    competitor_refs: Mapped[List["CompetitorRef"]] = relationship(
        "CompetitorRef", back_populates="strategy", cascade="all, delete-orphan"
    )

    __table_args__ = (
        Index("ix_marketing_strategies_user_status", "user_id", "status"),
    )


# ─── Brand Guideline Model ────────────────────────────────────────────────────

class BrandGuideline(Base):
    """
    Brand identity guidelines tied to a marketing strategy.
    Covers tone of voice, visual identity, messaging rules, etc.
    """
    __tablename__ = "brand_guidelines"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    strategy_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("marketing_strategies.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    category: Mapped[str] = mapped_column(
        String(100), nullable=False
    )  # e.g., "tone_of_voice", "visual_identity", "messaging", "hashtag_strategy"

    # Guideline content
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    rules: Mapped[Optional[list]] = mapped_column(JSONB, nullable=True, default=list)
    examples: Mapped[Optional[list]] = mapped_column(JSONB, nullable=True, default=list)
    do_list: Mapped[Optional[list]] = mapped_column(JSONB, nullable=True, default=list)
    dont_list: Mapped[Optional[list]] = mapped_column(JSONB, nullable=True, default=list)

    # Visual identity specifics
    primary_colors: Mapped[Optional[list]] = mapped_column(JSONB, nullable=True, default=list)
    secondary_colors: Mapped[Optional[list]] = mapped_column(JSONB, nullable=True, default=list)
    font_families: Mapped[Optional[list]] = mapped_column(JSONB, nullable=True, default=list)
    logo_usage_rules: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True)

    # Tone settings
    formality_level: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)  # 1–5
    personality_traits: Mapped[Optional[list]] = mapped_column(JSONB, nullable=True, default=list)
    forbidden_words: Mapped[Optional[list]] = mapped_column(JSONB, nullable=True, default=list)
    preferred_vocabulary: Mapped[Optional[list]] = mapped_column(JSONB, nullable=True, default=list)

    sort_order: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )

    # Relationships
    strategy: Mapped["MarketingStrategy"] = relationship(
        "MarketingStrategy", back_populates="brand_guidelines"
    )


# ─── Content Plan Model ───────────────────────────────────────────────────────

class ContentPlan(Base):
    """
    A time-bound content plan (editorial calendar) derived from a strategy.
    """
    __tablename__ = "content_plans"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    strategy_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("marketing_strategies.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    status: Mapped[ContentPlanStatus] = mapped_column(
        Enum(ContentPlanStatus), default=ContentPlanStatus.DRAFT, nullable=False
    )
    start_date: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    end_date: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    # AI-generated plan data
    planned_posts: Mapped[Optional[list]] = mapped_column(JSONB, nullable=True, default=list)
    content_calendar: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True, default=dict)
    themes: Mapped[Optional[list]] = mapped_column(JSONB, nullable=True, default=list)
    milestones: Mapped[Optional[list]] = mapped_column(JSONB, nullable=True, default=list)

    # Metrics targets
    target_posts_per_week: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    target_engagement_rate: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    target_follower_growth: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)

    ai_generated: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    ai_model_used: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )

    # Relationships
    strategy: Mapped["MarketingStrategy"] = relationship(
        "MarketingStrategy", back_populates="content_plans"
    )


# ─── Target Audience Model ────────────────────────────────────────────────────

class TargetAudience(Base):
    """
    Audience persona definition for a marketing strategy.
    """
    __tablename__ = "target_audiences"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    strategy_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("marketing_strategies.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    name: Mapped[str] = mapped_column(String(255), nullable=False)  # e.g. "Primary Persona - Tech Savvy Millennials"
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Demographics
    age_groups: Mapped[Optional[list]] = mapped_column(JSONB, nullable=True, default=list)
    genders: Mapped[Optional[list]] = mapped_column(JSONB, nullable=True, default=list)
    locations: Mapped[Optional[list]] = mapped_column(JSONB, nullable=True, default=list)
    languages: Mapped[Optional[list]] = mapped_column(JSONB, nullable=True, default=list)
    income_levels: Mapped[Optional[list]] = mapped_column(JSONB, nullable=True, default=list)
    education_levels: Mapped[Optional[list]] = mapped_column(JSONB, nullable=True, default=list)
    job_titles: Mapped[Optional[list]] = mapped_column(JSONB, nullable=True, default=list)
    industries: Mapped[Optional[list]] = mapped_column(JSONB, nullable=True, default=list)

    # Psychographics
    interests: Mapped[Optional[list]] = mapped_column(JSONB, nullable=True, default=list)
    pain_points: Mapped[Optional[list]] = mapped_column(JSONB, nullable=True, default=list)
    motivations: Mapped[Optional[list]] = mapped_column(JSONB, nullable=True, default=list)
    values: Mapped[Optional[list]] = mapped_column(JSONB, nullable=True, default=list)
    buying_behaviors: Mapped[Optional[list]] = mapped_column(JSONB, nullable=True, default=list)

    # Platform usage
    preferred_platforms: Mapped[Optional[list]] = mapped_column(JSONB, nullable=True, default=list)
    active_hours: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True, default=dict)
    content_preferences: Mapped[Optional[list]] = mapped_column(JSONB, nullable=True, default=list)

    is_primary: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    ai_generated: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )

    # Relationships
    strategy: Mapped["MarketingStrategy"] = relationship(
        "MarketingStrategy", back_populates="target_audiences"
    )


# ─── Business Goal Model ──────────────────────────────────────────────────────

class BusinessGoal(Base):
    """
    SMART business goals tied to a marketing strategy with KPI tracking.
    """
    __tablename__ = "business_goals"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    strategy_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("marketing_strategies.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    goal_type: Mapped[GoalType] = mapped_column(Enum(GoalType), nullable=False, index=True)
    status: Mapped[GoalStatus] = mapped_column(
        Enum(GoalStatus), default=GoalStatus.NOT_STARTED, nullable=False
    )

    # KPI definition
    metric_name: Mapped[str] = mapped_column(String(100), nullable=False)
    metric_unit: Mapped[str] = mapped_column(String(50), nullable=False)  # e.g., "followers", "%", "$"
    baseline_value: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    target_value: Mapped[float] = mapped_column(Float, nullable=False)
    current_value: Mapped[float] = mapped_column(Float, default=0.0, nullable=False)

    # Timeline
    due_date: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    achieved_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)

    # Progress tracking
    progress_percentage: Mapped[float] = mapped_column(Float, default=0.0, nullable=False)
    milestones: Mapped[Optional[list]] = mapped_column(JSONB, nullable=True, default=list)
    progress_history: Mapped[Optional[list]] = mapped_column(JSONB, nullable=True, default=list)

    sort_order: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )

    # Relationships
    strategy: Mapped["MarketingStrategy"] = relationship(
        "MarketingStrategy", back_populates="business_goals"
    )

    @property
    def progress(self) -> float:
        """Calculate progress % toward goal. Returns value between 0 and 100."""
        if not self.baseline_value:
            baseline = 0.0
        else:
            baseline = self.baseline_value
        total_required = self.target_value - baseline
        if total_required <= 0:
            return 100.0
        achieved = self.current_value - baseline
        return min(100.0, max(0.0, (achieved / total_required) * 100))


# ─── Competitor Reference Model ───────────────────────────────────────────────

class CompetitorRef(Base):
    """
    Competitor brands/accounts tracked as part of a marketing strategy.
    Used for competitive analysis and benchmarking.
    """
    __tablename__ = "competitor_refs"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    strategy_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("marketing_strategies.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    website_url: Mapped[Optional[str]] = mapped_column(String(500), nullable=True)
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    industry: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)

    # Platform handles for each social platform
    platform_handles: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True, default=dict)
    # e.g. {"twitter": "@competitorhandle", "instagram": "competitorhandle", ...}

    # Benchmarking data (updated by periodic sync tasks)
    follower_counts: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True, default=dict)
    engagement_rates: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True, default=dict)
    posting_frequency: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True, default=dict)
    top_content_types: Mapped[Optional[list]] = mapped_column(JSONB, nullable=True, default=list)
    estimated_reach: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True, default=dict)

    # AI analysis
    strengths: Mapped[Optional[list]] = mapped_column(JSONB, nullable=True, default=list)
    weaknesses: Mapped[Optional[list]] = mapped_column(JSONB, nullable=True, default=list)
    opportunities: Mapped[Optional[list]] = mapped_column(JSONB, nullable=True, default=list)
    threats: Mapped[Optional[list]] = mapped_column(JSONB, nullable=True, default=list)
    last_analyzed_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)

    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )

    # Relationships
    strategy: Mapped["MarketingStrategy"] = relationship(
        "MarketingStrategy", back_populates="competitor_refs"
    )

    __table_args__ = (
        UniqueConstraint("strategy_id", "name", name="uq_competitor_ref_strategy_name"),
    )
